/*!
 *=============================================================================================================
 *
 *  @file	simulate.c
 *
 *  @brief	Simulate DFN model of NMC battery
 *
 *=============================================================================================================
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "global.h"
#include "batt_model.h" // generated by batt_codegen.py
#include "integrator.h"


// Variable name same order as the exported var in python generator
const char *g_var_names[] = {
   "Voltage [V]",
   "Measured Current [A]",
   "Discharge capacity [A.h]",
   "Nominal cell capacity [A.h]",
   "X-averaged cell temperature [K]",
   "Anode potential [V]",
   "Cathode potential [V]",
   "Loss of lithium inventory [%]",
   "Loss of active material in negative electrode [%]",
   "Loss of active material in positive electrode [%]"
};



/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn         casadi_int len_from_sp(const casadi_int* sp) 
 *
 *  @brief      Helper function get dense vector length from sparsity (rows*cols)
 *
 *------------------------------------------------------------------------------------------------------------
 */
static
casadi_int len_from_sp(const casadi_int* sp)
{
    return sp[0] * sp[1]; // for dense vectors/matrices
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn		int dense_size_from_sparsity(const casadi_int *sp, int *nrow, int *ncol, int *nnz)
 *
 *  @brief	Convenience wrappers around CasADi function metadata
 *
 *------------------------------------------------------------------------------------------------------------
 */
static 
int dense_size_from_sparsity(const casadi_int *sp, int *nrow, int *ncol, int *nnz)
{
   *nrow = (int)sp[0];
   *ncol = (int)sp[1];
   const casadi_int *col = sp + 2;
   *nnz = (int)col[*ncol];
   return 0;
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn         double current_profile_GITT(double t)
 *
 *  @brief      Simple GITT-like current profile: 1 A for 10 s, 0 A for 90 s (period 100 s)
 *
 *------------------------------------------------------------------------------------------------------------
 */
static
double current_profile_GITT(double t)
{
   double phase = fmod(t, 100.0);
   return (phase < 10.0) ? 1.0 : 0.0; // discharge positive out of cell
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn         void eval_vars(double t, ModelCtx *ctx)
 *
 *  @bfief      Evaluate variables
 *
 *------------------------------------------------------------------------------------------------------------
 */
static
void eval_vars(double t, ModelCtx *ctx)
{
   const double *varg[variables_n_in()];
   double *vres[variables_n_out()];
   double t_now = t;

   varg[0] = &t_now;
   varg[1] = ctx->x;
   varg[2] = ctx->z;
   varg[3] = ctx->p;

   vres[0] = ctx->vars;

   variables(varg, vres, ctx->iw, ctx->w, 0);
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn		void max_work_mem(casadi_int *sz_iw, casadi_int *sz_w)
 *
 *  @brief	Max working memory
 *
 *------------------------------------------------------------------------------------------------------------
 */
void max_work_mem(casadi_int *sz_iw, casadi_int *sz_w)
{
   casadi_int arg_sz, res_sz, iw_sz, w_sz;

   x0_work(&arg_sz, &res_sz, &iw_sz, &w_sz);
   if (iw_sz > *sz_iw) *sz_iw = iw_sz;
   if (w_sz > *sz_w) *sz_w = w_sz;


   z0_work(&arg_sz, &res_sz, &iw_sz, &w_sz);
   if (iw_sz > *sz_iw) *sz_iw = iw_sz;
   if (w_sz > *sz_w) *sz_w = w_sz;

   variables_work(&arg_sz, &res_sz, &iw_sz, &w_sz);
   if (iw_sz > *sz_iw) *sz_iw = iw_sz;
   if (w_sz > *sz_w) *sz_w = w_sz;

   rhs__work(&arg_sz, &res_sz, &iw_sz, &w_sz);
   if (iw_sz > *sz_iw) *sz_iw = iw_sz;
   if (w_sz > *sz_w) *sz_w = w_sz;

   alg__work(&arg_sz, &res_sz, &iw_sz, &w_sz);
   if (iw_sz > *sz_iw) *sz_iw = iw_sz;
   if (w_sz > *sz_w) *sz_w = w_sz;

   jac_rhs_work(&arg_sz, &res_sz, &iw_sz, &w_sz);
   if (iw_sz > *sz_iw) *sz_iw = iw_sz;
   if (w_sz > *sz_w) *sz_w = w_sz;

   jac_alg_work(&arg_sz, &res_sz, &iw_sz, &w_sz);
   if (iw_sz > *sz_iw) *sz_iw = iw_sz;
   if (w_sz > *sz_w) *sz_w = w_sz;
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn		void ctx_create(ModelCtx *ctx)
 *
 *  @brief	Create CTX instance
 *
 *------------------------------------------------------------------------------------------------------------
 */
static
void ctx_create(ModelCtx *ctx)
{
    // --- Query sizes from one representative function ---
    ctx->nx    = len_from_sp(rhs__sparsity_out(0));            // len(dx/dt) == #diff. states
    ctx->nz    = len_from_sp(alg__sparsity_out(0));            // #alg residuals == #alg states
    ctx->np    = len_from_sp(rhs__sparsity_in(3));             // x0 takes only p
    ctx->nvars = len_from_sp(variables_sparsity_out(0));       // length of variables() stack


    // --- Allocate model buffers ---
    ctx->x    = (casadi_real*)calloc(ctx->nx,   sizeof(casadi_real));         // rhs
    ctx->z    = (casadi_real*)calloc(ctx->nz,   sizeof(casadi_real));         // residual state
    ctx->p    = (casadi_real*)calloc(ctx->np,   sizeof(casadi_real));         // parameters
    ctx->f    = (casadi_real*)calloc(ctx->nx,   sizeof(casadi_real));         // dx rhs
    ctx->g    = (casadi_real*)calloc(ctx->nz,   sizeof(casadi_real));         // algebraic residual
    ctx->vars = (casadi_real*)calloc(ctx->nvars, sizeof(casadi_real));        // variables() output

    // --- Variable names ---
    ctx->var_names = g_var_names;

    // --- Setup working memories ---
    max_work_mem(&ctx->iw_sz, &ctx->w_sz);
    ctx->iw = (casadi_int*)calloc(ctx->iw_sz, sizeof(casadi_int));
    ctx->w  = (casadi_real*)calloc(ctx->w_sz, sizeof(casadi_real));
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn		void ctx_init(ModelCtx *ctx)
 *
 *  @brief	Initialize CTX
 *
 *------------------------------------------------------------------------------------------------------------
 */
static 
void ctx_init(ModelCtx *ctx)
{
    // --- Initial conditions for x0() ---
    {
        const casadi_real* x0_arg[x0_n_in()];
        casadi_real*       x0_res[x0_n_out()];
        x0_arg[0] = ctx->p;
        x0_res[0] = ctx->x;
	memset(ctx->iw, 0, ctx->iw_sz*sizeof(casadi_int));
	memset(ctx->w, 0, ctx->w_sz*sizeof(casadi_real));
        x0(x0_arg, x0_res, ctx->iw, ctx->w, 0);
    }

    // --- Initial conditions for z0() ---
    {
        const casadi_real* z0_arg[z0_n_in()];
        casadi_real*       z0_res[z0_n_out()];
        z0_arg[0] = ctx->p;
        z0_res[0] = ctx->z;
	memset(ctx->iw, 0, ctx->iw_sz*sizeof(casadi_int));
	memset(ctx->w, 0, ctx->w_sz*sizeof(casadi_real));
        z0(z0_arg, z0_res, ctx->iw, ctx->w, 0);
    }

    eval_vars(0, ctx);
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *  
 *  @fn		void ctx_free(ModelCtx *ctx)
 *
 *  @brief	Free CTX object
 *
 *------------------------------------------------------------------------------------------------------------
 */
static 
void ctx_free(ModelCtx *ctx)
{
   if (ctx->vars) {free(ctx->vars); ctx->vars = NULL;}
   if (ctx->z)    {free(ctx->z); ctx->z = NULL;}
   if (ctx->x)    {free(ctx->x); ctx->x = NULL;}
   if (ctx->w)    {free(ctx->w); ctx->w = NULL;}
   if (ctx->iw)   {free(ctx->iw); ctx->iw = NULL;}
   if (ctx->p)    {free(ctx->p); ctx->p = NULL;}
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn		void f_eval(double *t, ModelCtx *ctx)
 *
 *  @brief	Evaluate f(t,x,z,u)
 *
 *------------------------------------------------------------------------------------------------------------
 */
static 
void f_eval(double *t, ModelCtx *ctx)
{
   const double *arg[rhs__n_in()]; 
   double *res[rhs__n_out()];

   arg[0] = t;
   arg[1] = ctx->x;
   arg[2] = ctx->z;
   arg[3] = ctx->p;

   res[0] = ctx->f;
   rhs_(arg, res, ctx->iw, ctx->w, 0);
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn		void g_eval(double *t, ModelCtx *ctx)
 *
 *  @brief	Evaluate g(x,z,u,t)
 *
 *------------------------------------------------------------------------------------------------------------
 */
static 
void g_eval(double *t, ModelCtx *ctx)
{
   const double *arg[alg__n_in()]; 
   double *res[alg__n_out()];

   arg[0] = t;
   arg[1] = ctx->x;
   arg[2] = ctx->z;
   arg[3] = ctx->p;

   res[0] = ctx->g;
   alg_(arg, res, ctx->iw, ctx->w, 0);
}


/*!
 *------------------------------------------------------------------------------------------------------------
 *
 *  @fn		void J_eval(double t, double h, const double *x, const double *z, const double *u, 
 *                          double *J, void *user)
 *
 *  @brief	Fill block Jacobian J for backward-Euler residual using jac_* outputs
 *
 *              In backward-euler we eant:
 *
 *                     |                       |    |             |
 *                     | I - h*f_x ;   -h*f_z  |    | J11  ;  J12 |
 *                 J = |                       |  = |             |
 *                     |    g_x    ;     g_z   |    | J21  ;  J22 |
 *                     |                       |    |             |
 *
 *                 J11 is nx * nx 
 *                 J12 is nx * nz
 *                 J21 is nz * nx
 *                 J22 is nz * nz
 *
 *------------------------------------------------------------------------------------------------------------
 */
static 
void J_eval(double *t, double h, ModelCtx *ctx, double *J)
{
   const int nx = ctx->nx;
   const int nz = ctx->nz;
   const int n = nx+nz;

   // 1)  Zero J and put identity in J11
   for(int i=0;i<n*n;++i) J[i]=0.0;
   for(int i=0;i<nx;++i) J[i*n + i] = 1.0;


   // ---- jac_rhs provides F1 block (df/dx and df/dz) in CSC format ----
   {
      const double *arg[jac_rhs_n_in()]; 
      double *res[jac_rhs_n_out()];
      arg[0] = t;
      arg[1] = ctx->x;
      arg[2] = ctx->z;
      arg[3] = ctx->p;

      // Get CSC compressed J 
      int nrow,ncol,nnz; 

      dense_size_from_sparsity(jac_rhs_sparsity_out(0), &nrow, &ncol, &nnz);
      double *values = (double*)malloc(nnz*sizeof(double));
      res[0] = values;                            // value holds CSC format
      jac_rhs(arg, res, ctx->iw, ctx->w, 0);

      // Rehydrate sparse J into dense J
      const casadi_int *sp = jac_rhs_sparsity_out(0);
      const casadi_int *col = sp+2; 
      const casadi_int *row = sp+2+ncol+1;

      int idx=0; 
      for(int j=0;j<ncol;++j)
      { 
         for(int k=col[j];k<col[j+1];++k)
	 { 
	    int i=row[k];
            if (j < nx)
               J[i*n + j] += -h*values[idx++];      // J11
            else
               J[i*n + (nx+j)] += -h*values[idx++]; // J12 
	 }
      }
   }

   // ---- jac_alg provides F2 block (dg/dx and dg/dz) in CSC compressed format ----
   {
      const double *arg[jac_alg_n_in()]; 
      double *res[jac_alg_n_out()];
      arg[0] = t;
      arg[1] = ctx->x;
      arg[2] = ctx->z;
      arg[3] = ctx->p;

      int base = nx;                  // start row of F2 block
      int nrow,ncol,nnz; 
      dense_size_from_sparsity(jac_alg_sparsity_out(0), &nrow, &ncol, &nnz);
      double *values = (double*)malloc((size_t)nnz*sizeof(double));

      res[0] = values; 
      jac_alg(arg, res, ctx->iw, ctx->w, 0);

      const casadi_int *sp = jac_alg_sparsity_out(0);
      const casadi_int *col = sp+2; 
      const casadi_int *row = sp+2+ncol+1;

      int idx=0; 
      for(int j=0;j<ncol;++j)
      { 
         for(int k=col[j]; k<col[j+1]; ++k)
	 { 
	    int i=row[k]; 
            J[(base+i)*(nx+nz) + j] += values[idx++];  // J21 & J22 same 'g' 
	 }
      }
   }
}



/*!
 *------------------------------------------------------------------------------------------------------------
 *  Main logic
 *------------------------------------------------------------------------------------------------------------
 */
int main(void)
{
   int rc;
   double t = 0;
   const double dt = 0.001; 		// seconds
   const double t_end_cap = 1000.0; 	// safety cap for demo
   const double Tamb_K = 298.15; 	// 25 C

   // Init the CTX
   ModelCtx ctx = {0}; 
   ctx_create(&ctx);
   printf("nx=%d, nz=%d, np=%d, nvars=%d\n", ctx.nx, ctx.nz, ctx.np, ctx.nvars);

   int nrow, ncol, nnz;
   dense_size_from_sparsity(jac_rhs_sparsity_out(0), &nrow, &ncol, &nnz);
   printf("jac_rhs: nrow = %d, ncol=%d, nnz=%d\n", nrow, ncol, nnz); 
   dense_size_from_sparsity(jac_alg_sparsity_out(0), &nrow, &ncol, &nnz);
   printf("jac_alg: nrow = %d, ncol=%d, nnz=%d\n", nrow, ncol, nnz); 


   // Must init the input parameters
   ctx.p[0] = current_profile_GITT(t);
   ctx.p[1] = Tamb_K;
   ctx_init(&ctx);


   // Integrator wiring
   DaeSystem sys = {0};
   sys.nx = (size_t)ctx.nx; 
   sys.nz = (size_t)ctx.nz; 
   sys.np = (size_t)ctx.np; 
   sys.user = (void *)&ctx;
   sys.f = f_eval; 
   sys.g = (ctx.nz >0) ? g_eval: NULL;
   sys.J = J_eval;

   DaeSettings cfg = {
      .newton_tol=1e-8, 
      // .newton_max_iter=18, 
      .newton_max_iter=30, 
      .fd_eps=1e-6, 
      .verbose=0
   };


   // CSV header
   printf("time_s,current_A,SOC,SOH,voltage_V,anode_V,cathode_V,LAM_neg_pct,LAM_pos_pct,LLI_pct,temp_K\n");
   double Q_total_init = ctx.vars[IDX_Q_NOM];


   // Main time loop
   while (t <= t_end_cap) 
   {
      // Inputs at t+dt (backward Euler uses t_{n+1})
      double t_next = t + dt;
      ctx.p[0] = current_profile_GITT(t_next);
      ctx.p[1] = Tamb_K;

      int rc = dae_step_backward_euler(&sys, &cfg, &t_next, dt, &ctx);
      if (rc != 0)
      {
         fprintf(stderr, "Integrator failed at t=%.6f, rc=%d\n", t_next, rc);
         break;
      }
      t = t_next;

      // Evaluate variables() at (t,x,z,u)
      eval_vars(t, &ctx);

      // Compute SOC and SOH
      double Qdis = ctx.vars[IDX_Q_DIS];
      double Qtot = ctx.vars[IDX_Q_NOM];
      double SOC = fmax(0.0, 1.0 - (Qdis/(Qtot>1e-12?Qtot:1.0)));
      double SOH = (Q_total_init>0)? (Qtot / Q_total_init) : 1.0;

      // Emit CSV row
      printf("%.2f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f\n",
              t,
              ctx.vars[IDX_CURRENT], 
	      SOC, 
	      SOH,
              ctx.vars[IDX_VOLTAGE], 
	      ctx.vars[IDX_N_V], 
	      ctx.vars[IDX_P_V],
              ctx.vars[IDX_N_LAM], 
              ctx.vars[IDX_P_LAM], 
	      ctx.vars[IDX_LLI],
              ctx.vars[IDX_AVG_CELL_TEMP]);


      // Terminate if voltage below 3.0 V
      if (ctx.vars[IDX_VOLTAGE] < 3.0) break;
      if (t >= 1000.0) break; // also stop at 1000 s as requested
   }

   ctx_free(&ctx);

   return 0;
}   


