/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int rhs_(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int rhs__alloc_mem(void);
int rhs__init_mem(int mem);
void rhs__free_mem(int mem);
int rhs__checkout(void);
void rhs__release(int mem);
void rhs__incref(void);
void rhs__decref(void);
casadi_int rhs__n_in(void);
casadi_int rhs__n_out(void);
casadi_real rhs__default_in(casadi_int i);
const char* rhs__name_in(casadi_int i);
const char* rhs__name_out(casadi_int i);
const casadi_int* rhs__sparsity_in(casadi_int i);
const casadi_int* rhs__sparsity_out(casadi_int i);
int rhs__work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int rhs__work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define rhs__SZ_ARG 7
#define rhs__SZ_RES 2
#define rhs__SZ_IW 0
#define rhs__SZ_W 5168
int alg_(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int alg__alloc_mem(void);
int alg__init_mem(int mem);
void alg__free_mem(int mem);
int alg__checkout(void);
void alg__release(int mem);
void alg__incref(void);
void alg__decref(void);
casadi_int alg__n_in(void);
casadi_int alg__n_out(void);
casadi_real alg__default_in(casadi_int i);
const char* alg__name_in(casadi_int i);
const char* alg__name_out(casadi_int i);
const casadi_int* alg__sparsity_in(casadi_int i);
const casadi_int* alg__sparsity_out(casadi_int i);
int alg__work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int alg__work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define alg__SZ_ARG 7
#define alg__SZ_RES 2
#define alg__SZ_IW 0
#define alg__SZ_W 3521
int jac_rhs(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int jac_rhs_alloc_mem(void);
int jac_rhs_init_mem(int mem);
void jac_rhs_free_mem(int mem);
int jac_rhs_checkout(void);
void jac_rhs_release(int mem);
void jac_rhs_incref(void);
void jac_rhs_decref(void);
casadi_int jac_rhs_n_in(void);
casadi_int jac_rhs_n_out(void);
casadi_real jac_rhs_default_in(casadi_int i);
const char* jac_rhs_name_in(casadi_int i);
const char* jac_rhs_name_out(casadi_int i);
const casadi_int* jac_rhs_sparsity_in(casadi_int i);
const casadi_int* jac_rhs_sparsity_out(casadi_int i);
int jac_rhs_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int jac_rhs_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define jac_rhs_SZ_ARG 9
#define jac_rhs_SZ_RES 3
#define jac_rhs_SZ_IW 843
#define jac_rhs_SZ_W 20429
int jac_alg(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int jac_alg_alloc_mem(void);
int jac_alg_init_mem(int mem);
void jac_alg_free_mem(int mem);
int jac_alg_checkout(void);
void jac_alg_release(int mem);
void jac_alg_incref(void);
void jac_alg_decref(void);
casadi_int jac_alg_n_in(void);
casadi_int jac_alg_n_out(void);
casadi_real jac_alg_default_in(casadi_int i);
const char* jac_alg_name_in(casadi_int i);
const char* jac_alg_name_out(casadi_int i);
const casadi_int* jac_alg_sparsity_in(casadi_int i);
const casadi_int* jac_alg_sparsity_out(casadi_int i);
int jac_alg_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int jac_alg_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define jac_alg_SZ_ARG 7
#define jac_alg_SZ_RES 3
#define jac_alg_SZ_IW 843
#define jac_alg_SZ_W 12112
int x0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int x0_alloc_mem(void);
int x0_init_mem(int mem);
void x0_free_mem(int mem);
int x0_checkout(void);
void x0_release(int mem);
void x0_incref(void);
void x0_decref(void);
casadi_int x0_n_in(void);
casadi_int x0_n_out(void);
casadi_real x0_default_in(casadi_int i);
const char* x0_name_in(casadi_int i);
const char* x0_name_out(casadi_int i);
const casadi_int* x0_sparsity_in(casadi_int i);
const casadi_int* x0_sparsity_out(casadi_int i);
int x0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int x0_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define x0_SZ_ARG 2
#define x0_SZ_RES 2
#define x0_SZ_IW 0
#define x0_SZ_W 1534
int z0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int z0_alloc_mem(void);
int z0_init_mem(int mem);
void z0_free_mem(int mem);
int z0_checkout(void);
void z0_release(int mem);
void z0_incref(void);
void z0_decref(void);
casadi_int z0_n_in(void);
casadi_int z0_n_out(void);
casadi_real z0_default_in(casadi_int i);
const char* z0_name_in(casadi_int i);
const char* z0_name_out(casadi_int i);
const casadi_int* z0_sparsity_in(casadi_int i);
const casadi_int* z0_sparsity_out(casadi_int i);
int z0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int z0_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define z0_SZ_ARG 2
#define z0_SZ_RES 2
#define z0_SZ_IW 0
#define z0_SZ_W 992
int variables(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int variables_alloc_mem(void);
int variables_init_mem(int mem);
void variables_free_mem(int mem);
int variables_checkout(void);
void variables_release(int mem);
void variables_incref(void);
void variables_decref(void);
casadi_int variables_n_in(void);
casadi_int variables_n_out(void);
casadi_real variables_default_in(casadi_int i);
const char* variables_name_in(casadi_int i);
const char* variables_name_out(casadi_int i);
const casadi_int* variables_sparsity_in(casadi_int i);
const casadi_int* variables_sparsity_out(casadi_int i);
int variables_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int variables_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define variables_SZ_ARG 7
#define variables_SZ_RES 2
#define variables_SZ_IW 0
#define variables_SZ_W 6240
#ifdef __cplusplus
} /* extern "C" */
#endif
